// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: servers/battle/proto/battle.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BattleOverEvent_State int32

const (
	BattleOverEvent_Finished  BattleOverEvent_State = 0
	BattleOverEvent_Disbanded BattleOverEvent_State = 1
	BattleOverEvent_Timeover  BattleOverEvent_State = 2
)

// Enum value maps for BattleOverEvent_State.
var (
	BattleOverEvent_State_name = map[int32]string{
		0: "Finished",
		1: "Disbanded",
		2: "Timeover",
	}
	BattleOverEvent_State_value = map[string]int32{
		"Finished":  0,
		"Disbanded": 1,
		"Timeover":  2,
	}
)

func (x BattleOverEvent_State) Enum() *BattleOverEvent_State {
	p := new(BattleOverEvent_State)
	*p = x
	return p
}

func (x BattleOverEvent_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BattleOverEvent_State) Descriptor() protoreflect.EnumDescriptor {
	return file_servers_battle_proto_battle_proto_enumTypes[0].Descriptor()
}

func (BattleOverEvent_State) Type() protoreflect.EnumType {
	return &file_servers_battle_proto_battle_proto_enumTypes[0]
}

func (x BattleOverEvent_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BattleOverEvent_State.Descriptor instead.
func (BattleOverEvent_State) EnumDescriptor() ([]byte, []int) {
	return file_servers_battle_proto_battle_proto_rawDescGZIP(), []int{7, 0}
}

type EmptyMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyMessage) Reset() {
	*x = EmptyMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servers_battle_proto_battle_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyMessage) ProtoMessage() {}

func (x *EmptyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_servers_battle_proto_battle_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyMessage.ProtoReflect.Descriptor instead.
func (*EmptyMessage) Descriptor() ([]byte, []int) {
	return file_servers_battle_proto_battle_proto_rawDescGZIP(), []int{0}
}

type PlayerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid    int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	SeatId int32 `protobuf:"varint,2,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	Score  int32 `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
}

func (x *PlayerInfo) Reset() {
	*x = PlayerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servers_battle_proto_battle_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInfo) ProtoMessage() {}

func (x *PlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_servers_battle_proto_battle_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInfo.ProtoReflect.Descriptor instead.
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return file_servers_battle_proto_battle_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerInfo) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PlayerInfo) GetSeatId() int32 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

func (x *PlayerInfo) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type BattleConfigure struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ttf int32 `protobuf:"varint,3,opt,name=ttf,proto3" json:"ttf,omitempty"` // 游戏最大进行时间, 单位: second
}

func (x *BattleConfigure) Reset() {
	*x = BattleConfigure{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servers_battle_proto_battle_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BattleConfigure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleConfigure) ProtoMessage() {}

func (x *BattleConfigure) ProtoReflect() protoreflect.Message {
	mi := &file_servers_battle_proto_battle_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleConfigure.ProtoReflect.Descriptor instead.
func (*BattleConfigure) Descriptor() ([]byte, []int) {
	return file_servers_battle_proto_battle_proto_rawDescGZIP(), []int{2}
}

func (x *BattleConfigure) GetTtf() int32 {
	if x != nil {
		return x.Ttf
	}
	return 0
}

type CreateBattleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameName    string           `protobuf:"bytes,1,opt,name=game_name,json=gameName,proto3" json:"game_name,omitempty"`
	GameConf    []byte           `protobuf:"bytes,2,opt,name=game_conf,json=gameConf,proto3" json:"game_conf,omitempty"`
	BattleConf  *BattleConfigure `protobuf:"bytes,3,opt,name=battle_conf,json=battleConf,proto3" json:"battle_conf,omitempty"`
	PlayerInfos []*PlayerInfo    `protobuf:"bytes,4,rep,name=player_infos,json=playerInfos,proto3" json:"player_infos,omitempty"`
}

func (x *CreateBattleRequest) Reset() {
	*x = CreateBattleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servers_battle_proto_battle_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBattleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBattleRequest) ProtoMessage() {}

func (x *CreateBattleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servers_battle_proto_battle_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBattleRequest.ProtoReflect.Descriptor instead.
func (*CreateBattleRequest) Descriptor() ([]byte, []int) {
	return file_servers_battle_proto_battle_proto_rawDescGZIP(), []int{3}
}

func (x *CreateBattleRequest) GetGameName() string {
	if x != nil {
		return x.GameName
	}
	return ""
}

func (x *CreateBattleRequest) GetGameConf() []byte {
	if x != nil {
		return x.GameConf
	}
	return nil
}

func (x *CreateBattleRequest) GetBattleConf() *BattleConfigure {
	if x != nil {
		return x.BattleConf
	}
	return nil
}

func (x *CreateBattleRequest) GetPlayerInfos() []*PlayerInfo {
	if x != nil {
		return x.PlayerInfos
	}
	return nil
}

type CreateBattleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BattleId string `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
}

func (x *CreateBattleResponse) Reset() {
	*x = CreateBattleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servers_battle_proto_battle_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBattleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBattleResponse) ProtoMessage() {}

func (x *CreateBattleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_servers_battle_proto_battle_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBattleResponse.ProtoReflect.Descriptor instead.
func (*CreateBattleResponse) Descriptor() ([]byte, []int) {
	return file_servers_battle_proto_battle_proto_rawDescGZIP(), []int{4}
}

func (x *CreateBattleResponse) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

type WatcherJoinBattleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BattleId    string        `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	PlayerInfos []*PlayerInfo `protobuf:"bytes,4,rep,name=player_infos,json=playerInfos,proto3" json:"player_infos,omitempty"`
}

func (x *WatcherJoinBattleRequest) Reset() {
	*x = WatcherJoinBattleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servers_battle_proto_battle_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatcherJoinBattleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatcherJoinBattleRequest) ProtoMessage() {}

func (x *WatcherJoinBattleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servers_battle_proto_battle_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatcherJoinBattleRequest.ProtoReflect.Descriptor instead.
func (*WatcherJoinBattleRequest) Descriptor() ([]byte, []int) {
	return file_servers_battle_proto_battle_proto_rawDescGZIP(), []int{5}
}

func (x *WatcherJoinBattleRequest) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

func (x *WatcherJoinBattleRequest) GetPlayerInfos() []*PlayerInfo {
	if x != nil {
		return x.PlayerInfos
	}
	return nil
}

type WatcherJoinBattleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WatcherJoinBattleResponse) Reset() {
	*x = WatcherJoinBattleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servers_battle_proto_battle_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatcherJoinBattleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatcherJoinBattleResponse) ProtoMessage() {}

func (x *WatcherJoinBattleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_servers_battle_proto_battle_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatcherJoinBattleResponse.ProtoReflect.Descriptor instead.
func (*WatcherJoinBattleResponse) Descriptor() ([]byte, []int) {
	return file_servers_battle_proto_battle_proto_rawDescGZIP(), []int{6}
}

type BattleOverEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State BattleOverEvent_State                  `protobuf:"varint,1,opt,name=state,proto3,enum=battle.BattleOverEvent_State" json:"state,omitempty"`
	Tally map[int32]*BattleOverEvent_BattleScore `protobuf:"bytes,2,rep,name=tally,proto3" json:"tally,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *BattleOverEvent) Reset() {
	*x = BattleOverEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servers_battle_proto_battle_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BattleOverEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleOverEvent) ProtoMessage() {}

func (x *BattleOverEvent) ProtoReflect() protoreflect.Message {
	mi := &file_servers_battle_proto_battle_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleOverEvent.ProtoReflect.Descriptor instead.
func (*BattleOverEvent) Descriptor() ([]byte, []int) {
	return file_servers_battle_proto_battle_proto_rawDescGZIP(), []int{7}
}

func (x *BattleOverEvent) GetState() BattleOverEvent_State {
	if x != nil {
		return x.State
	}
	return BattleOverEvent_Finished
}

func (x *BattleOverEvent) GetTally() map[int32]*BattleOverEvent_BattleScore {
	if x != nil {
		return x.Tally
	}
	return nil
}

type BattleMessageWrap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BattleId string `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	Uid      int64  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Topic    string `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	Data     []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *BattleMessageWrap) Reset() {
	*x = BattleMessageWrap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servers_battle_proto_battle_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BattleMessageWrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleMessageWrap) ProtoMessage() {}

func (x *BattleMessageWrap) ProtoReflect() protoreflect.Message {
	mi := &file_servers_battle_proto_battle_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleMessageWrap.ProtoReflect.Descriptor instead.
func (*BattleMessageWrap) Descriptor() ([]byte, []int) {
	return file_servers_battle_proto_battle_proto_rawDescGZIP(), []int{8}
}

func (x *BattleMessageWrap) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

func (x *BattleMessageWrap) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *BattleMessageWrap) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *BattleMessageWrap) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type BattleOverEvent_BattleScore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Score int64             `protobuf:"varint,1,opt,name=score,proto3" json:"score,omitempty"`
	Ex    map[string]string `protobuf:"bytes,2,rep,name=ex,proto3" json:"ex,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *BattleOverEvent_BattleScore) Reset() {
	*x = BattleOverEvent_BattleScore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servers_battle_proto_battle_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BattleOverEvent_BattleScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleOverEvent_BattleScore) ProtoMessage() {}

func (x *BattleOverEvent_BattleScore) ProtoReflect() protoreflect.Message {
	mi := &file_servers_battle_proto_battle_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleOverEvent_BattleScore.ProtoReflect.Descriptor instead.
func (*BattleOverEvent_BattleScore) Descriptor() ([]byte, []int) {
	return file_servers_battle_proto_battle_proto_rawDescGZIP(), []int{7, 0}
}

func (x *BattleOverEvent_BattleScore) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *BattleOverEvent_BattleScore) GetEx() map[string]string {
	if x != nil {
		return x.Ex
	}
	return nil
}

var File_servers_battle_proto_battle_proto protoreflect.FileDescriptor

var file_servers_battle_proto_battle_proto_rawDesc = []byte{
	0x0a, 0x21, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x2f, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x06, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x22, 0x0e, 0x0a, 0x0c, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x4d, 0x0a, 0x0a, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x73,
	0x65, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x65,
	0x61, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x23, 0x0a, 0x0f, 0x42, 0x61,
	0x74, 0x74, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x74, 0x74, 0x66, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x74, 0x74, 0x66, 0x22,
	0xc0, 0x01, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x63, 0x6f, 0x6e,
	0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x6e,
	0x66, 0x12, 0x38, 0x0a, 0x0b, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x66,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x2e,
	0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x52,
	0x0a, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x12, 0x35, 0x0a, 0x0c, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x73, 0x22, 0x33, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x74, 0x74,
	0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x61,
	0x74, 0x74, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62,
	0x61, 0x74, 0x74, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x6e, 0x0a, 0x18, 0x57, 0x61, 0x74, 0x63, 0x68,
	0x65, 0x72, 0x4a, 0x6f, 0x69, 0x6e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x49, 0x64,
	0x12, 0x35, 0x0a, 0x0c, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x2e,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x22, 0x1b, 0x0a, 0x19, 0x57, 0x61, 0x74, 0x63, 0x68,
	0x65, 0x72, 0x4a, 0x6f, 0x69, 0x6e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0xad, 0x03, 0x0a, 0x0f, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x4f,
	0x76, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x33, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65,
	0x2e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x4f, 0x76, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x38, 0x0a,
	0x05, 0x74, 0x61, 0x6c, 0x6c, 0x79, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x62,
	0x61, 0x74, 0x74, 0x6c, 0x65, 0x2e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x4f, 0x76, 0x65, 0x72,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x54, 0x61, 0x6c, 0x6c, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x05, 0x74, 0x61, 0x6c, 0x6c, 0x79, 0x1a, 0x97, 0x01, 0x0a, 0x0b, 0x42, 0x61, 0x74, 0x74,
	0x6c, 0x65, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x3b, 0x0a,
	0x02, 0x65, 0x78, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x62, 0x61, 0x74, 0x74,
	0x6c, 0x65, 0x2e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x4f, 0x76, 0x65, 0x72, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x2e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x45,
	0x78, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x02, 0x65, 0x78, 0x1a, 0x35, 0x0a, 0x07, 0x45, 0x78,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x1a, 0x5d, 0x0a, 0x0a, 0x54, 0x61, 0x6c, 0x6c, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x39, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x23, 0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x2e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65,
	0x4f, 0x76, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65,
	0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x22, 0x32, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x46, 0x69, 0x6e,
	0x69, 0x73, 0x68, 0x65, 0x64, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x44, 0x69, 0x73, 0x62, 0x61,
	0x6e, 0x64, 0x65, 0x64, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x76,
	0x65, 0x72, 0x10, 0x02, 0x22, 0x6c, 0x0a, 0x11, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x57, 0x72, 0x61, 0x70, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x61, 0x74,
	0x74, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x61,
	0x74, 0x74, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69,
	0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x32, 0xb1, 0x01, 0x0a, 0x06, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x12, 0x4b, 0x0a,
	0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x12, 0x1b, 0x2e,
	0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x74,
	0x74, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x62, 0x61, 0x74,
	0x74, 0x6c, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5a, 0x0a, 0x11, 0x57, 0x61,
	0x74, 0x63, 0x68, 0x65, 0x72, 0x4a, 0x6f, 0x69, 0x6e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x12,
	0x20, 0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x2e, 0x57, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72,
	0x4a, 0x6f, 0x69, 0x6e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x21, 0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x2e, 0x57, 0x61, 0x74, 0x63, 0x68,
	0x65, 0x72, 0x4a, 0x6f, 0x69, 0x6e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x1e, 0x5a, 0x1c, 0x2e, 0x2f, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x73, 0x2f, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_servers_battle_proto_battle_proto_rawDescOnce sync.Once
	file_servers_battle_proto_battle_proto_rawDescData = file_servers_battle_proto_battle_proto_rawDesc
)

func file_servers_battle_proto_battle_proto_rawDescGZIP() []byte {
	file_servers_battle_proto_battle_proto_rawDescOnce.Do(func() {
		file_servers_battle_proto_battle_proto_rawDescData = protoimpl.X.CompressGZIP(file_servers_battle_proto_battle_proto_rawDescData)
	})
	return file_servers_battle_proto_battle_proto_rawDescData
}

var file_servers_battle_proto_battle_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_servers_battle_proto_battle_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_servers_battle_proto_battle_proto_goTypes = []interface{}{
	(BattleOverEvent_State)(0),          // 0: battle.BattleOverEvent.State
	(*EmptyMessage)(nil),                // 1: battle.EmptyMessage
	(*PlayerInfo)(nil),                  // 2: battle.PlayerInfo
	(*BattleConfigure)(nil),             // 3: battle.BattleConfigure
	(*CreateBattleRequest)(nil),         // 4: battle.CreateBattleRequest
	(*CreateBattleResponse)(nil),        // 5: battle.CreateBattleResponse
	(*WatcherJoinBattleRequest)(nil),    // 6: battle.WatcherJoinBattleRequest
	(*WatcherJoinBattleResponse)(nil),   // 7: battle.WatcherJoinBattleResponse
	(*BattleOverEvent)(nil),             // 8: battle.BattleOverEvent
	(*BattleMessageWrap)(nil),           // 9: battle.BattleMessageWrap
	(*BattleOverEvent_BattleScore)(nil), // 10: battle.BattleOverEvent.BattleScore
	nil,                                 // 11: battle.BattleOverEvent.TallyEntry
	nil,                                 // 12: battle.BattleOverEvent.BattleScore.ExEntry
}
var file_servers_battle_proto_battle_proto_depIdxs = []int32{
	3,  // 0: battle.CreateBattleRequest.battle_conf:type_name -> battle.BattleConfigure
	2,  // 1: battle.CreateBattleRequest.player_infos:type_name -> battle.PlayerInfo
	2,  // 2: battle.WatcherJoinBattleRequest.player_infos:type_name -> battle.PlayerInfo
	0,  // 3: battle.BattleOverEvent.state:type_name -> battle.BattleOverEvent.State
	11, // 4: battle.BattleOverEvent.tally:type_name -> battle.BattleOverEvent.TallyEntry
	12, // 5: battle.BattleOverEvent.BattleScore.ex:type_name -> battle.BattleOverEvent.BattleScore.ExEntry
	10, // 6: battle.BattleOverEvent.TallyEntry.value:type_name -> battle.BattleOverEvent.BattleScore
	4,  // 7: battle.Battle.CreateBattle:input_type -> battle.CreateBattleRequest
	6,  // 8: battle.Battle.WatcherJoinBattle:input_type -> battle.WatcherJoinBattleRequest
	5,  // 9: battle.Battle.CreateBattle:output_type -> battle.CreateBattleResponse
	7,  // 10: battle.Battle.WatcherJoinBattle:output_type -> battle.WatcherJoinBattleResponse
	9,  // [9:11] is the sub-list for method output_type
	7,  // [7:9] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_servers_battle_proto_battle_proto_init() }
func file_servers_battle_proto_battle_proto_init() {
	if File_servers_battle_proto_battle_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_servers_battle_proto_battle_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servers_battle_proto_battle_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servers_battle_proto_battle_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BattleConfigure); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servers_battle_proto_battle_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBattleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servers_battle_proto_battle_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBattleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servers_battle_proto_battle_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WatcherJoinBattleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servers_battle_proto_battle_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WatcherJoinBattleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servers_battle_proto_battle_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BattleOverEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servers_battle_proto_battle_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BattleMessageWrap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servers_battle_proto_battle_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BattleOverEvent_BattleScore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_servers_battle_proto_battle_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_servers_battle_proto_battle_proto_goTypes,
		DependencyIndexes: file_servers_battle_proto_battle_proto_depIdxs,
		EnumInfos:         file_servers_battle_proto_battle_proto_enumTypes,
		MessageInfos:      file_servers_battle_proto_battle_proto_msgTypes,
	}.Build()
	File_servers_battle_proto_battle_proto = out.File
	file_servers_battle_proto_battle_proto_rawDesc = nil
	file_servers_battle_proto_battle_proto_goTypes = nil
	file_servers_battle_proto_battle_proto_depIdxs = nil
}
